spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: account_route
          uri: lb://account-server
          predicates:
            - Path=/account/**
        - id: auth_route
          uri: lb://auth-server
          predicates:
            - Path=/auth/**
        - id: transfer_route
          uri: lb://transfer2-server
          predicates:
            - Path=/transfer/**
        - id: currency_route
          uri: lb://currency-server
          predicates:
            - Path=/currency/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    config:
      import: optional:configserver:http://localhost:8888