spring:
  application:
    name: currency-server
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka/
jwt:
  secret: your-secret-key
  expiration: 86400000