version: '3.8'

services:
  auth-db:
    image: postgres:15
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: alimurad
      POSTGRES_PASSWORD: alimurad05
    ports:
      - "5432:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: auth_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  auth_postgres_data:
